apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: nodejob
spec:
  completions: 10 # if you wanted to run the same job ten times one after one
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - node
        - -v
        image: node
        name: nodejob
        resources: {}
      restartPolicy: Never
status: {}
