apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello world; echo $APPNAME; sleep 3600
    image: busybox
    name: testpod
    env:
    - name: APPNAME
      valueFrom:
        configMapKeyRef:
          name: testcm
          key: appname
# Created a pod that refers a configmap as an environment variable
# the configmap was predefined 

