apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    bu: bu1
    env: prod
    run: nginx
  name: mysvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    bu: bu1
    env: prod
    run: nginx
status:
  loadBalancer: {}
